name: traffic_sign_recognition_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8  # Specify the Python version
  - opencv>=4.5.0  # OpenCV for image processing
  - numpy>=1.19.5  # NumPy for numerical operations
  - pandas>=1.1.5  # Pandas for data manipulation
  - pillow>=8.4.0  # Pillow for image handling
  - matplotlib>=3.3.4  # Matplotlib for plotting
  - scikit-learn>=0.24.2  # Scikit-learn for machine learning
  - scikit-image>=0.18.1  # Scikit-image for image processing
  - imutils>=0.5.4  # Imutils for convenience functions
  - pip 
  - pip:
    - tensorflow>=2.4.1 # TensorFlow for deep learning
